declare module "@context/GlobalContext";
declare module "@components/portfolio/Card";
declare module "@components/portfolio/Technologies";
declare module "@hooks/useMediaQuery";
declare module "@hooks/useEffectCard";
declare module "@hooks/types";
declare module "@images/close.png"
declare module "@images/master.jpg"
declare module "@utils/functions";
declare module "@public/assets/imageSkeleton.svg";
declare module "@components/Anchor";
